# Generated by Django 5.2.4 on 2025-07-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='prescribed_medications',
            field=models.TextField(blank=True),
        ),
    ]
