# Generated by Django 4.2.23 on 2025-07-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patientrecord_prescribed_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='diastolic_bp',
            field=models.IntegerField(blank=True, help_text='Diastolic blood pressure (mmHg)', null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='oxygen_saturation',
            field=models.IntegerField(blank=True, help_text='Oxygen saturation (%)', null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='pulse_rate',
            field=models.IntegerField(blank=True, help_text='Pulse rate (beats per minute)', null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, help_text='Respiratory rate (breaths per minute)', null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='systolic_bp',
            field=models.IntegerField(blank=True, help_text='Systolic blood pressure (mmHg)', null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in °C', max_digits=4, null=True),
        ),
    ]
